on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

name: Delete stack

jobs:
  deploy:
    name: Delete stack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - name: Install required packages and delete stack
        run: |
          pip install boto3 python-dotenv
          cd jmeter-icap-poc/scripts
          sed -i -e '/AWS_PROFILE_NAME/ { d; } ' config.env
          python3 delete_stack.py
        env:
          PREFIX: "ga" # ${{ secrets.PREFIX }}
